### ISSUE TITLE
HTTPDigestAuth @get_password authentication needs improvements 

### ISSUE THREAD

**Issue by kasanitej** [miguelgrinberg/Flask-HTTPAuth#113]
So "get_password" is expecting a raw password. We do store passwords in SHA256 and we even dont know how to retrieve a actual password from that hash value. So the function can be improved to accomodate that.

**Comment by miguelgrinberg** [comment]
The `get_password` callback is the old way of handling authentication, it is maintained in the codebase for legacy apps, but it should not be used for new apps.

See the `verify_password` callback in the documentation for the proper and most secure way of handling your password verification.

**Comment by kasanitej** [comment]
But verify password belongs to HTTPBasicAuth not HTTPDigestAuth. Am I missing something here?

**Comment by miguelgrinberg** [comment]
Oh, sorry about that, missed the reference to digest, I assumed you were talking about basic auth.

So digest auth hasn't been very active, I actually haven't heard of anybody using it in a long time. I would need to re-read the spec to remember all the details, but as far as I remember, both the client and the server need to calculate their hashes using the raw password.

The digest class has an option that you can use to provide the calculated "ha1" hash instead of the raw password. Have you seen that? If you store the "ha1" for each user, then you can return that as the password, as long as you set `use_ha1_pw=True` when you create your digest object.

**Comment by kasanitej** [comment]
Hi,

Thanks it is still doesnt work.

I copied this snippet from [wikipedia](https://en.wikipedia.org/wiki/Digest_access_authentication)
> In September 2015, RFC 7616 replaced RFC 2617 by adding 4 new algorithms: "SHA-256", "SHA-256-sess", "SHA-512" and "SHA-512-sess". The encoding is equivalent to "MD5" and "MD5-sess" algorithms, with MD5 hashing function replaced with SHA-256 and SHA-512.

Any improvement to accomodate the above will help users who uses SHA256/512 for passwords

**Comment by miguelgrinberg** [comment]
@kasanitej Do browsers support SHA 256/512? I thought most browsers only support MD5.

**Comment by kasanitej** [comment]
Yeah... may be it is not... anyway thanks.... I am just learning about the old Authentication systems.. I can see why people discourage this technique.

**Comment by miguelgrinberg** [comment]
I'm going to close this as it does not seem necessary at this point to implement additional hashing functions since browsers have not adopted them (at least Chrome hasn't). I'm open to reconsider if this changes in the future.
