### ISSUE TITLE
Flask_httpauth installation not working with pip but worked with pip3

### ISSUE THREAD

**Issue by ankit-gautam23** [miguelgrinberg/Flask-HTTPAuth#158]
error: 'egg_base' must be a directory name (got 'src') flask httpauth installation error

**Comment by miguelgrinberg** [comment]
pip and pip3 are the same tool, there's no difference. The issue is that you probably have a mixture of Python releases installed, so pip goes to one version of Python and pip3 goes to another.

My recommendation is that you install this and all other packages in a virtual environment, which should eliminate cross-version issues.

**Comment by ankit-gautam23** [comment]
Very Insightful, Thanks for your response.
