### ISSUE TITLE
anyway to allow token somewhere and disallow token elsewhere?

### ISSUE THREAD

**Issue by fyears** [miguelgrinberg/Flask-HTTPAuth#16]
For example,

```python
@auth.verify_password
def verify_password(email_or_token='', password=''):
    pass

@app.route('/users/<username>/', methods=['GET','POST','PUT','DELETE'])
@auth.login_required
def user_all(username):
    # general info
    # allowing auth with username+password or token
    pass

@app.route('/users/<username>/tokens/', methods=['POST', 'DELETE'])
@auth.login_required
def user_token(username):
    # manage tokens
    # only allowing auth with username+password
    pass
```

In the above routes (resources), I would like to:
allow users manage general info using username+password or tokens,
allow users manage tokens using username+password, but NOT tokens here.

In fact, GitHub API is designed like this. :-)

Is there anyway to do this with `Flask-HTTPAuth`?

**Comment by miguelgrinberg** [comment]
@fyears Yes, there are a couple of ways to do this. One possibility is how I solved this in my book. See https://github.com/miguelgrinberg/flasky/blob/master/app/api_1_0/authentication.py for the relevant code. Here I set a `g.token_used` boolean in the password verification callback, so that I can dismiss token authenticated calls when I only want to allow username+password.

Another option that is possible a bit cleaner is to define two Flask-HTTPAuth instances, each with its own verify password callback. One of them can allow username+password or token, while the other only allows username+password. You can then decorate each route using the decorator from the level of authentication you want.

**Comment by fyears** [comment]
@miguelgrinberg Two instances! I forget this simplest way! Thank you!
