### ISSUE TITLE
HTTPDigestAuth raise TypeError when get_password() returns None.

### ISSUE THREAD

**Issue by kennytm** [miguelgrinberg/Flask-HTTPAuth#5]
If we implement `@auth.get_password` as described in the doc:

``` python
@auth.get_password
def get_pw(username):
    if username in users:
        return users[username]
    return None
```

When the user logs in with an invalid user name, the script with raise an error:

```
  File ".../env/lib/python3.3/site-packages/flask_httpauth.py", line 52, in decorated
    if not self.authenticate(auth, password):
  File ".../env/lib/python3.3/site-packages/flask_httpauth.py", line 108, in authenticate
    a1 = auth.username + ":" + auth.realm + ":" + password
TypeError: Can't convert 'NoneType' object to str implicitly
```

(BTW the test suite does not catch this because it simply makes every invalid user's password being `'other'`. This is totally wrong, and should return some non-string  to indicate unconditional rejection.)

**Comment by sergiy-kozak** [comment]
Hi,
maybe my question is not directly to this issue, but anyway. You said, that since digest module requires session storage, it would make a lot more sense to use server-side sessions. I would like still to see how it (digest auth)  can be done in case of the default configuration, where this is about working with cookie that Flask sends back to client. Do you have examples how to demonstrate digest http auth, using some client like curl?

**Comment by miguelgrinberg** [comment]
I don't have an example ready, but you can look at the unit test code for an example app. To use curl you do the same thing you do for basic auth, but add `--digest` to make it use the digest protocol.
