### ISSUE TITLE
Question: is there any way to see if I logged in templates?

### ISSUE THREAD

**Issue by somenxavier** [miguelgrinberg/Flask-HTTPAuth#50]
Hi,

I use [digest auth](http://flask-httpauth.readthedocs.io/en/latest/#digest-authentication-example). I wonder if I could see if I logged or not in *templates*.

**Comment by miguelgrinberg** [comment]
The `flask.g` variable is available on your templates, so anything you add to it can be checked there.

**Comment by somenxavier** [comment]
Can you document its use?

**Comment by somenxavier** [comment]
I want something like:
```
{% if you-are-identified %} Admin here {% endif %}
```

**Comment by miguelgrinberg** [comment]
This is really not something I can document, because I have no way to know what is the structure of your user object, and how you log users in.

If in the verify password callback you do something like:

    if <credentials are valid>:
        g.current_user = <get the user that corresponds to the credentials given>
    else:
        g.current_user = None

then in a template you can check if the user logged in with:

    {% if g.current_user %}
        <p>the user is logged in</p>
    {% else %}
        <p>the user is not logged in</p>
    {% endif %}

**Comment by somenxavier** [comment]
I not understood

**Comment by somenxavier** [comment]
You can document assuming we are using your [example](https://flask-httpauth.readthedocs.io/en/latest/#digest-authentication-example)

**Comment by miguelgrinberg** [comment]
In the example you referenced you are always logged in. A user that does not provide authentication will not be given access at all.

**Comment by somenxavier** [comment]
So. Can you use this example as based example for document it

2017-01-28 22:46 GMT+01:00 Miguel Grinberg <notifications@github.com>:

**Comment by miguelgrinberg** [comment]
I still don't understand what you want to document. The endpoint in the example will never run if the user does not provide valid credentials, so any time the endpoint runs you have a logged in user.

**Comment by somenxavier** [comment]
Okay. Let's clear this definitevely. Based on your [example](http://flask-httpauth.readthedocs.io/en/latest/#digest-authentication-example):

```
@app.route("/admin/start", methods=['GET'])
@auth.login_required
def admin_start():
	return render_template('admin_home.html')

@app.route("/home/start", methods=['GET'])
def home_start():
	return render_template('home_home.html')

So you are in `admin_start` if you are logged. But you can be in `home_start` anyway. In `home_home.html` template I want to know if you are previously logged or not:

```
<h1>Home</h1>

[contents]
{% if you_are_logged %} display some secret {% endif %}
```

**Comment by miguelgrinberg** [comment]
Okay, now I see why we couldn't agree on this. I think you have a misunderstanding on how HTTP Authentication works.

This type of authentication is stateless, which means there is no "memory" of a user login. Each time the client sends a request, it needs to provide credentials. Your `/admin/start` endpoint will only execute if the client provides valid credentials. Within the context of that request, you can find who the user is with `auth.username()`, but checking if the user is an admin is pointless, since any users that are not admins were already turned away by Flask-HTTPAuth.

The `/home/start` endpoint, however, is not protected with any auth. Any client that invokes this request will be given access, no questions asked. There is nothing in the HTTP Authentication protocol that allows you to "remember" that a client was given access to the admin endpoint, later when it sends a request to the regular endpoint. That's not how HTTP Auth works.

If you want the user status as an admin to be remembered when the user navigates to the non-admin portion of your application, then you have to implement that as part of your application. You can either set a cookie, or use an extension such as Flask-Login which will set a cookie up for you.

**Comment by somenxavier** [comment]
But my browser does not ask again the password when I visit admin. So it remembers.

**Comment by miguelgrinberg** [comment]
@somenxavier Yes, that is correct. The browser will remember your credentials, but that is a browser feature, on the server the password needs to be given with every request.
