### ISSUE TITLE
Token verification callback is always called

### ISSUE THREAD

**Issue by brunoais** [miguelgrinberg/Flask-HTTPAuth#62]
Is it by design that, for all requests, the callback user function decorated with `@auth.verify_token` is called for the `AuthToken`?
If so, why?

**Comment by miguelgrinberg** [comment]
Yes. The idea is that instead of blocking a client with a 401, you may decide to let them in after you set your state appropriately, for example by putting a flag on `flask.g` to indicate that the user is anonymous.

**Comment by brunoais** [comment]
Makes sense, although I question the design choice of the empty string instead of `None` to tell that there is no token.

**Comment by miguelgrinberg** [comment]
Yes, I agree that it is a bit strange. It all started when I added support for basic auth in which the password or the username were missing. The callback would then be invoked with an empty string for the missing component. Not really by design but by the mere fact that 'username:'.split(':')` returns an empty string for the second element. The rest is just to keep consistent with that.

**Comment by brunoais** [comment]
I see. With such explanation makes sense, then
