### ISSUE TITLE
Digest Authentication with Edge browser

### ISSUE THREAD

**Issue by c-goes** [miguelgrinberg/Flask-HTTPAuth#94]
I'm testing the extension with the old Edge browser (without Chromium).

Using the example for Digest authentication, the Edge browser is probably not sending the correct Header line. The server repeats 401 Error codes even when Login is correct.

It could be a bug in Edge.

**Comment by miguelgrinberg** [comment]
Unfortunately I do not have access to a machine with Edge. You will need to debug this further to determine if there is anything wrong. I assume there is a console where you can see requests and their headers, so please review an exchange between Edge and the server and reopen if the problem is not on the Edge side.

**Comment by c-goes** [comment]
This is probably caused by edge itself. The example works when one changes the URI from / to something else. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by csreddyennam** [comment]
I too see same problem, please let me know
